name: Supabase Keep-Alive

on:
  schedule:
    - cron: '30 5 * * 1'
  workflow_dispatch:

jobs:
  ping-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase Database
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE极速加速器最新版下载_ANON_KEY }}
        run: |
          echo "Pinging Supabase database"
          echo "URL: $SUPABASE_URL"
          
          response=$(curl -s -w "%{http_code}" \
            --request GET \
            --url "${SUPABASE_URL}/rest/v1/keep_alive_pings?select=*&limit=1" \
            --header "apikey: ${SUPABASE_ANON_KEY}" \
            --header "Authorization: Bearer ${SUPABASE_ANON_KEY}")
          
          http_code=${response: -3}
          
          if [ "$http_code" -eq 200 ]; then
            echo "Success: $http_code"
          elif [ "$http_code" -eq 404 ]; then
            echo "Table not found"
            exit 1
          else
            echo "Failed: $http_code"
            exit 1
          fi