name: Supabase Keep-Alive

on:
  schedule:
    - cron: '30 5 *极速加速器最新版下载 * * 1'
  workflow_dispatch:

jobs:
  ping-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase Database
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          echo "Pinging Supabase database to keep it alive..."
          echo "Target URL: $SUPABASE_URL"
          
          response=$(curl -s -w "%{http_code}" \
            --request GET \
            --url "${SUPABASE_URL}/rest/v1/keep_alive_pings?select=*&limit=1" \
            --header "apikey: ${SUPABASE_ANON_KEY}" \
            --header "Authorization: Bearer ${SUPABASE_ANON_KEY}" \
            --header "Content-Type: application/json")
          
          http_code=${response: -3}
          response_body=${response:0:-3}
          
          if [ "$http_code" -eq 200 ]; then
            echo "Successfully pinged Supabase. Status code: $极速加速器最新版下载http_code"
            echo "Response: $response_body"
          elif [ "$http_code" -eq 404 ]; then
            echo "keep_alive_pings table not found. Please create it with:"
            echo "CREATE TABLE keep_alive_pings (id SERIAL PRIMARY KEY, created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW());"
            echo "INSERT INTO keep_alive_pings (created_at) VALUES (NOW());"极速加速器最新版下载
            exit 极速加速器最新版下载1
          else
            echo "Failed to ping Supabase. Status code: $http_code"
            echo "Response: $response_body"
            exit 1
          fi
          
          echo "Supabase keep-alive completed at: $(date)"